### ISSUE TITLE
Settings Form fill control 

### ISSUE THREAD

**Issue by DenisShaikin** [app-generator/flask-volt-dashboard#3]
Hello, how to add a function for **settings** form filling control? 

@blueprint.route('/settings', methods=['GET', 'POST'])
@login_required
def settings_form():
     print(request)
     return render_template('settings.html', user=current_user, form=form)

**never works** even if I add in route_template(template) condition for settings.html page:

        if segment not in ['settings.html']:
                return render_template( template, segment=segment )

Thanx in advance

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
