### ISSUE TITLE
Plot Data on Dashboard

### ISSUE THREAD

**Issue by Damon0603** [app-generator/flask-volt-dashboard#8]
Hi , I was wondering how to implement a matplotlib plot on the dashboard with own data. Is there an easy approach ? 

Cheers

**Comment by app-generator** [comment]
Hello @Damon0603 

Can you tell us more regarding this use case? 

Here is a simple `Flask &MatplotLIB` usage that generates an image on-the-fly

https://stackoverflow.com/questions/50728328/python-how-to-show-matplotlib-in-flask

**Comment by Damon0603** [comment]
Hey thank you for your response. 

Well I have trouble plotting data like this.

`import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os


df = pd.read_csv('AAPL_Montly_updates.csv',sep =",", index_col='Date') 

df['Adj Close'].plot(figsize=(10,8))
plt.title('Closing price')`

I would like to show a simple plot in the app. I somehow can´t find a proper solution to that. 


html is like the template : 
`
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<body>
<div>
   Hallo
    </div>
</body>
{% include "includes/footer.html" %}

{% endblock content %}

 
{% block javascripts %}{% endblock javascripts %}`

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
